version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FIREBASE_API_KEY=your-firebase-api-key
      - FIREBASE_AUTH_DOMAIN=your-firebase-auth-domain
      - FIREBASE_PROJECT_ID=your-firebase-project-id
      - FIREBASE_STORAGE_BUCKET=your-firebase-storage-bucket
      - FIREBASE_MESSAGING_SENDER_ID=your-firebase-messaging-sender-id
      - FIREBASE_APP_ID=your-firebase-app-id
    volumes:
      - .:/usr/src/app
